import './styles.css';

// Import Wails bindings (auto-generated by wails dev)
import {
    GetStats,
    GetHealth,
    GetUptime,
    GetConfig,
    GetProviders,
    AddProvider,
    UpdateProvider,
    RemoveProvider,
    TestProvider,
    TestArbitraryProvider,
    SwitchProvider,
    DiscoverModels,
    GetModels,
    ActivateModel,
    UpdateSetting,
    GetLogs,
    ExportConfig,
    ExportLogs,
    MinimizeWindow,
    MaximizeWindow,
    CloseWindow,
    ConfirmDelete,
    ShowAlert,
} from '../wailsjs/go/main/App';

// ── API Wrapper ──────────────────────────────────────────────────────────────
const API = {
    async getStats()           { return await GetStats(); },
    async getHealth()          { return await GetHealth(); },
    async getUptime()          { return await GetUptime(); },
    async getConfig()          { return await GetConfig(); },
    async getProviders()       { return await GetProviders(); },
    async addProvider(p)       { return await AddProvider(p); },
    async updateProvider(i, p) { return await UpdateProvider(i, p); },
    async removeProvider(i)    { return await RemoveProvider(i); },
    async testProvider(i)      { return await TestProvider(i); },
    async TestArbitraryProvider(n, u, k, m) { return await TestArbitraryProvider(n, u, k, m); },
    async switchProvider(i)    { return await SwitchProvider(i); },
    async discoverModels()     { return await DiscoverModels(); },
    async getModels()          { return await GetModels(); },
    async activateModel(m, p)  { return await ActivateModel(m, p); },
    async updateSetting(k, v)  { return await UpdateSetting(k, v); },
    async getLogs(limit)       { return await GetLogs(limit); },
    async exportConfig()       { return await ExportConfig(); },
    async exportLogs()         { return await ExportLogs(); },
    async confirmDelete(t, m)  { return await ConfirmDelete(t, m); },
    async showAlert(t, m)      { return await ShowAlert(t, m); },
    minimizeWindow()           { MinimizeWindow(); },
    maximizeWindow()           { MaximizeWindow(); },
    closeWindow()              { CloseWindow(); },
};
window.API = API;

async function nativeConfirm(msg) {
    return await API.confirmDelete('Claude Proxy Pro', msg);
}

async function nativeAlert(msg) {
    await API.showAlert('Claude Proxy Pro', msg);
}

// ── State ────────────────────────────────────────────────────────────────────
let currentModelFilter = 'all';
let currentProviderFilter = 'all';
let modelSortField = 'id';
let modelSortDir = 1;
let currentModels = [];
let currentProviders = [];
let currentLogSort = 'timestamp';
let currentLogSortDir = -1;

// Mascot & Active Model UI
class MascotController {
    constructor() {
        this.crab = document.getElementById('crabMascot');
        this.bubble = document.getElementById('crabBubble');
        this.screen = document.querySelector('.tamagotchi-screen');
        this.idleTimer = null;
        this.sleepTimer = null;
        this.isSleeping = false;
        this.lastActivity = Date.now();
        this.animations = ['animating-walk', 'animating-sway', 'animating-bounce', 'animating-flip'];
        
        if (!this.crab) return;
        
        // Activity tracking for sleep mode
        document.addEventListener('mousemove', () => this.wakeUp());
        document.addEventListener('click', () => this.wakeUp());
        document.addEventListener('keydown', () => this.wakeUp());
        
        this.startIdleLoop();
        this.checkSleep();
    }

    startIdleLoop() {
        if (this.idleTimer) clearInterval(this.idleTimer);
        this.idleTimer = setInterval(() => {
            if (this.isSleeping) return;
            // 40% chance to do a random idle animation
            if (Math.random() < 0.4) {
                const anim = this.animations[Math.floor(Math.random() * this.animations.length)];
                this.playAnim(anim, 1500);
            }
        }, 5000);
    }

    checkSleep() {
        if (this.sleepTimer) clearInterval(this.sleepTimer);
        this.sleepTimer = setInterval(() => {
            if (!this.isSleeping && Date.now() - this.lastActivity > 60000) { // 1 min sleep
                this.isSleeping = true;
                this.crab.className = 'crab-mascot sleeping';
                this.setBubble('Zzz', 'sleep', true);
            }
        }, 10000);
    }

    wakeUp() {
        this.lastActivity = Date.now();
        if (this.isSleeping) {
            this.isSleeping = false;
            this.crab.className = 'crab-mascot';
            this.crab.classList.remove('show-bubble');
            this.playAnim('animating-jump', 500); // Wake up jump!
        }
    }

    playAnim(animClass, duration) {
        if (this.isSleeping) return;
        this.crab.className = 'crab-mascot';
        void this.crab.offsetWidth; // force reflow
        this.crab.classList.add(animClass);
        setTimeout(() => {
            if (!this.isSleeping) this.crab.className = 'crab-mascot';
        }, duration);
    }

    setBubble(text, styleClass, persistent = false) {
        if (!this.bubble) return;
        this.bubble.textContent = text;
        this.bubble.className = 'crab-bubble ' + (styleClass || '');
        this.crab.classList.add('show-bubble');
        if (!persistent) {
            setTimeout(() => {
                this.crab.classList.remove('show-bubble');
            }, 2000);
        }
    }

    triggerSuccess(msg = '✔ OK!') {
        this.wakeUp();
        this.screen.classList.remove('flash-green');
        void this.screen.offsetWidth;
        this.screen.classList.add('flash-green');
        setTimeout(() => this.screen.classList.remove('flash-green'), 500);
        
        this.playAnim('animating-dance', 1000);
        this.setBubble(msg, '');
    }

    triggerError(msg = '⚠ Error') {
        this.wakeUp();
        this.screen.classList.remove('flash-red');
        void this.screen.offsetWidth;
        this.screen.classList.add('flash-red');
        setTimeout(() => this.screen.classList.remove('flash-red'), 500);
        
        this.playAnim('animating-jump', 500);
        this.setBubble(msg, 'error');
    }
}

let Mascot = null;

document.addEventListener('DOMContentLoaded', () => {
    Mascot = new MascotController();
});

function updateActiveModelText(providers, activeIdx) {
    if (providers && providers.length > activeIdx) {
        const activeProv = providers[activeIdx];
        window.activeModelId = activeProv.model;
        window.activeProviderName = activeProv.name;
        const display = document.getElementById('activeModelDisplay');
        if (display) display.textContent = activeProv.model;
    }
}

async function restoreNativeClaude() {
    try {
        if (!confirm("Are you sure you want to remove the terminal integration and restore native Claude Code behavior?")) return;
        const msg = await window.go.main.App.RestoreNativeClaude();
        if (Mascot) Mascot.triggerSuccess("Restored!");
        alert(msg);
    } catch (e) {
        if (Mascot) Mascot.triggerError("Failed!");
        alert("Failed to restore native Claude: " + e);
    }
}

// ── Navigation ───────────────────────────────────────────────────────────────
function showPage(id) {
    document.querySelectorAll('.page').forEach(p => p.classList.remove('active'));
    document.querySelectorAll('.nav-item').forEach(n => n.classList.remove('active'));
    document.getElementById('page-' + id).classList.add('active');
    // Find and activate the nav item
    document.querySelectorAll('.nav-item').forEach(n => {
        if (n.dataset.page === id) n.classList.add('active');
    });
    if (id === 'models') loadModels();
    if (id === 'providers') loadProviders();
    if (id === 'settings') loadSettings();
}

// ── Dashboard ────────────────────────────────────────────────────────────────
async function loadDashboard() {
    try {
        const stats = await API.getStats();
        const health = await API.getHealth();
        const providers = await API.getProviders();
        const pc = document.getElementById('providerCards');

        document.getElementById('statRequests').textContent = formatNum(stats.total_requests || 0);
        document.getElementById('statLatency').textContent = (stats.avg_latency_ms || 0) + 'ms';
        document.getElementById('statTokens').textContent = formatNum((stats.total_input_tokens || 0) + (stats.total_output_tokens || 0));

        // Stability
        const errRate = stats.total_requests > 0 ? (health.total_errors / stats.total_requests * 100) : 0;
        const healthPct = Math.max(0, 100 - errRate * 5);
        const hb = document.getElementById('healthBar');
        hb.style.width = healthPct + '%';
        hb.style.background = healthPct > 80 ? 'var(--green)' : healthPct > 50 ? 'var(--yellow)' : 'var(--red)';
        document.getElementById('totalErrors').textContent = health.total_errors || 0;
        document.getElementById('totalRetries').textContent = health.total_retries || 0;
        document.getElementById('totalFailovers').textContent = health.total_failovers || 0;

        // Uptime
        document.getElementById('uptimeBadge').textContent = stats.uptime || '--';

        // Status
        const isHealthy = health.is_healthy;
        const dot = document.getElementById('statusDot');
        dot.className = 'status-dot ' + (isHealthy ? 'online' : (providers.some(p => p.status === 'degraded') ? 'degraded' : 'offline'));
        document.getElementById('statusText').textContent = isHealthy ? 'Connected' : 'Degraded';

        // Toggles
        updateToggle('autoRetryToggle', health.auto_retry);
        updateToggle('failoverToggle', health.failover);

        const pn = document.getElementById('providerNodes');
        if (!providers || providers.length === 0) {
            if (pn) pn.innerHTML = '<p style="color:var(--text-dim);padding:20px;text-align:center">No active nodes.</p>';
        } else {
            if (pn) {
                pn.innerHTML = providers.map((p, i) => {
                    const statusCls = p.status === 'online' ? 'online' : p.status === 'degraded' ? 'degraded' : 'offline';
                    const isActive = i === health.active_idx;
                    const activeTxt = isActive ? ' <span style="font-size:0.7rem;color:var(--accent);margin-left:8px">★ Active</span>' : '';
                    return '<div class="node-item">' +
                           '<div><span class="node-name">' + esc(p.name) + '</span>' + activeTxt + '</div>' +
                           '<div class="node-status ' + statusCls + '" title="' + p.status + '"></div>' +
                           '</div>';
                }).join('');
            }
        }

        const pf = document.getElementById('providerFilter');
        if (pf && providers) {
            const currentSel = pf.value || 'all';
            pf.innerHTML = '<option value="all" style="background:var(--bg)">All Providers</option>' + 
                           providers.map(p => '<option value="' + esc(p.name) + '" style="background:var(--bg)">' + esc(p.name) + '</option>').join('');
            if (providers.some(p => p.name === currentSel)) {
                pf.value = currentSel;
            } else {
                pf.value = 'all';
                currentProviderFilter = 'all';
            }
        }

        currentProviders = providers;
        window.currentProviders = providers;
        updateActiveModelText(providers, health.active_idx);
    } catch(e) {
        console.error('Dashboard error:', e);
        fetch('http://localhost:8082/api/debug-log', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                type: 'dashboard-error',
                message: String(e.message || e),
                stack: String(e.stack || '')
            })
        }).catch(() => {});
        document.getElementById('statusDot').className = 'status-dot offline';
        document.getElementById('statusText').textContent = 'Disconnected';
    }
}

async function loadLogs() {
    try {
        const logs = await API.getLogs(200);
        const el = document.getElementById('requestLog');
        if (!logs || logs.length === 0) {
            el.innerHTML = '<div class="empty-feed"><div class="pulse-dot"></div><p style="font-family: var(--font-mono); font-size: 0.85rem; letter-spacing: 0.5px;">Awaiting Neural Link on Port 8081...</p></div>';
            return;
        }
        el.innerHTML = logs.slice(0, 50).map(l => {
            const t = new Date(l.timestamp).toLocaleTimeString();
            const statusCls = l.status < 400 ? 'success' : 'error';
            return '<div class="log-entry">' +
                '<span class="log-time">' + t + '</span>' +
                '<span class="log-provider">' + esc(l.provider || '--') + '</span>' +
                '<span class="log-model">' + esc(l.model || '--') + '</span>' +
                '<span class="log-status ' + statusCls + '">' + l.status + '</span>' +
                '<span class="log-latency">' + l.latency_ms + 'ms</span>' +
                '<span class="log-tokens">⬆' + (l.input_tokens || 0) + ' ⬇' + (l.output_tokens || 0) + '</span>' +
            '</div>';
        }).join('');
    } catch(e) {}
}

// ── Models ───────────────────────────────────────────────────────────────────
async function loadModels() {
    try {
        currentModels = await API.getModels();
        // Fetch health and providers to know which one is active
        const health = await API.getHealth();
        const providers = await API.getProviders();
        if (providers && health && providers.length > health.active_idx) {
            updateActiveModelText(providers, health.active_idx);
        }
        renderModels();
    } catch(e) {}
}

function renderModels() {
    const search = (document.getElementById('modelSearch')?.value || '').toLowerCase();
    let filtered = currentModels.filter(m => {
        if (currentModelFilter !== 'all' && m.pricing !== currentModelFilter) return false;
        if (currentProviderFilter !== 'all' && m.provider !== currentProviderFilter) return false;
        if (search && !m.id.toLowerCase().includes(search) && !m.provider.toLowerCase().includes(search)) return false;
        return true;
    });

    filtered.sort((a, b) => {
        const av = a[modelSortField] || '';
        const bv = b[modelSortField] || '';
        if (typeof av === 'number') return (av - bv) * modelSortDir;
        return String(av).localeCompare(String(bv)) * modelSortDir;
    });

    const tbody = document.getElementById('modelsList');
    if (!filtered.length) {
        tbody.innerHTML = '<div style="text-align:center;color:var(--text-dim);padding:40px">No models found. Add providers and discover models.</div>';
        return;
    }
    tbody.innerHTML = filtered.map(m => {
        const isActive = (m.id === window.activeModelId && m.provider === window.activeProviderName);
        const actionBtn = isActive 
            ? '<button class="btn-activate">Active ✔</button>'
            : '<button class="btn-activate" onclick="activateModel(\'' + esc(m.id) + '\',\'' + esc(m.provider) + '\')">Activate</button>';
            
        const ctx = m.context_size ? formatNum(m.context_size) : '--';
        const lat = m.latency_ms || '--';
        const latColor = lat < 200 ? 'var(--green)' : lat < 500 ? 'var(--yellow)' : 'var(--text-dim)';
        
        return '<div class="model-row ' + (isActive ? 'active-row' : '') + '">' +
            '<div class="m-name-col">' +
                '<span class="m-title">' + esc(m.id) + '</span>' +
                '<span class="m-provider-badge">' + esc(m.provider) + '</span>' +
            '</div>' +
            '<div class="m-stats-col">' +
                '<span class="m-stat-pill">' + ctx + '</span>' +
                '<span class="m-type-badge ' + m.pricing + '">' + String(m.pricing).toUpperCase() + '</span>' +
                '<span class="m-stat-pill" style="color:' + latColor + '">' + lat + 'ms</span>' +
            '</div>' +
            '<div class="m-action-col">' + actionBtn + '</div>' +
        '</div>';
    }).join('');
}

function setModelFilter(f, el) {
    currentModelFilter = f;
    document.querySelectorAll('#page-models .seg-item').forEach(c => c.classList.remove('active'));
    el.classList.add('active');
    renderModels();
}

function setProviderFilter() {
    currentProviderFilter = document.getElementById('providerFilter').value;
    renderModels();
}

function sortModels(field) {
    if (modelSortField === field) modelSortDir *= -1;
    else { modelSortField = field; modelSortDir = 1; }
    renderModels();
}

// ── Providers ────────────────────────────────────────────────────────────────
async function loadProviders() {
    try {
        currentProviders = await API.getProviders();
        window.currentProviders = currentProviders;
        renderProviders();
    } catch(e) {}
}

function renderProviders() {
    const tbody = document.getElementById('providersList');
    if (!currentProviders.length) {
        tbody.innerHTML = '<div style="text-align:center;color:var(--text-dim);padding:40px">No providers configured. Click "Add Provider" to get started.</div>';
        return;
    }
    tbody.innerHTML = currentProviders.map((p, i) => {
        const lat = p.latency_ms || 0;
        const latCls = lat < 200 && lat > 0 ? 'good' : lat < 500 && lat > 0 ? 'warn' : lat === 0 ? '' : 'bad';
        
        let rate = 0;
        if (p.success_count + p.fail_count > 0) {
            rate = Math.round((p.success_count / (p.success_count + p.fail_count)) * 100);
        }
        const rateCls = rate > 90 ? 'good' : rate > 70 ? 'warn' : rate > 0 ? 'bad' : '';

        return '<div class="provider-rack ' + p.status + '">' +
            '<div class="pr-identity">' +
                '<span class="pr-name">' + esc(p.name) + '</span>' +
                '<span class="pr-url">' + esc(p.url) + '</span>' +
            '</div>' +
            '<div class="pr-metrics">' +
                '<div class="pr-metric">' +
                    '<span class="pr-m-lbl">Latency</span>' +
                    '<span class="pr-m-val ' + latCls + '">' + lat + 'ms</span>' +
                '</div>' +
                '<div class="pr-metric">' +
                    '<span class="pr-m-lbl">Success Rate</span>' +
                    '<div class="pr-progress-track" title="' + rate + '%">' +
                        '<div class="pr-progress-fill ' + rateCls + '" style="width:' + rate + '%"></div>' +
                    '</div>' +
                '</div>' +
                '<div class="pr-metric">' +
                    '<span class="pr-m-lbl">Priority</span>' +
                    '<span class="pr-m-val">' + p.priority + '</span>' +
                '</div>' +
            '</div>' +
            '<div class="pr-actions">' +
                '<div class="btn-icon" onclick="editProvider(' + i + ')" title="Edit">' +
                    '<svg fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24" style="width:16px;height:16px"><path stroke-linecap="round" stroke-linejoin="round" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"/></svg>' +
                '</div>' +
                '<div class="btn-icon" onclick="testFromList(' + i + ')" title="Test Connection">' +
                    '<svg fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24" style="width:16px;height:16px"><path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/></svg>' +
                '</div>' +
                '<div class="btn-icon danger" onclick="removeProvider(' + i + ')" title="Delete">' +
                    '<svg fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24" style="width:16px;height:16px"><path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>' +
                '</div>' +
            '</div>' +
        '</div>';
    }).join('');
}

function showAddProvider() {
    document.getElementById('editIdx').value = -1;
    document.getElementById('modalTitle').textContent = 'Add Provider';
    document.getElementById('pName').value = '';
    document.getElementById('pUrl').value = '';
    document.getElementById('pKey').value = '';
    document.getElementById('pModel').value = '';
    document.getElementById('pPriority').value = '1';
    document.getElementById('addModal').classList.add('show');
}

function editProvider(idx) {
    const p = currentProviders[idx];
    document.getElementById('editIdx').value = idx;
    document.getElementById('modalTitle').textContent = 'Edit Provider';
    document.getElementById('pName').value = p.name;
    document.getElementById('pUrl').value = p.url;
    document.getElementById('pKey').value = p.key || '';
    document.getElementById('pModel').value = p.model;
    document.getElementById('pPriority').value = p.priority;
    document.getElementById('addModal').classList.add('show');
}

function hideAddProvider() { document.getElementById('addModal').classList.remove('show'); }

async function saveProvider() {
    const idx = parseInt(document.getElementById('editIdx').value);
    const data = {
        name: document.getElementById('pName').value,
        url: document.getElementById('pUrl').value,
        key: document.getElementById('pKey').value,
        model: document.getElementById('pModel').value,
        priority: parseInt(document.getElementById('pPriority').value) || 1
    };
    if (!data.name || !data.url || !data.key) {
        nativeAlert('Name, URL, and API Key are required');
        return;
    }

    try {
        if (idx >= 0) {
            await API.updateProvider(idx, data);
        } else {
            await API.addProvider(data);
        }
        hideAddProvider();
        loadProviders();
        loadDashboard();
        
        // Automatically sync models from the new/updated provider!
        discoverAll();
    } catch(e) { nativeAlert('Failed to save provider'); }
}

async function testCurrentProvider() {
    const name = document.getElementById('pName').value || 'Test';
    const url = document.getElementById('pUrl').value;
    const key = document.getElementById('pKey').value;
    const model = document.getElementById('pModel').value || '';
    
    if (!url || !key) {
        nativeAlert('URL and API Key are required to test.');
        return;
    }
    
    const btn = document.querySelector('.btn-secondary[onclick="testCurrentProvider()"]');
    if (btn) btn.innerHTML = 'Testing...';
    
    try {
        const result = await API.TestArbitraryProvider(name, url, key, model);
        if (btn) btn.innerHTML = '<svg fill="none" stroke="currentColor" viewBox="0 0 24 24" width="14" height="14"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg> Test';
        
        if (result.error) {
            nativeAlert('Test Failed!\nError: ' + result.error);
        } else {
            nativeAlert('Test Successful! ✅\nStatus: ' + result.status + '\nModels Found: ' + result.model_count);
        }
    } catch (e) {
        if (btn) btn.innerHTML = '<svg fill="none" stroke="currentColor" viewBox="0 0 24 24" width="14" height="14"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg> Test';
        nativeAlert('Test failed to execute: ' + e);
    }
}

async function removeProvider(idx) {
    if (!await nativeConfirm('Remove provider "' + currentProviders[idx].name + '"?')) return;
    try {
        await API.removeProvider(idx);
        loadProviders();
        loadDashboard();
    } catch(e) { nativeAlert('Failed to remove provider'); }
}

async function testFromList(idx) {
    try {
        const result = await API.testProvider(idx);
        if (result.error) {
            Mascot?.triggerError('Test Failed');
        } else {
            Mascot?.triggerSuccess('Test OK');
        }
        nativeAlert('Status: ' + result.status + '\nLatency: ' + result.latency_ms + 'ms\nModels: ' + result.model_count + (result.error ? '\nError: ' + result.error : ''));
    } catch(e) { 
        Mascot?.triggerError('Test Failed');
        nativeAlert('Test failed'); 
    }
}

async function discoverAll() {
    try {
        await API.discoverModels();
        Mascot?.triggerSuccess('Scanning...');
        nativeAlert('Model discovery complete. Refreshing lists.');
        loadProviders();
        loadModels();
    } catch(e) {
        Mascot?.triggerError('Scan Failed');
    }
}

async function switchProvider(idx) {
    try {
        await API.switchProvider(idx);
        Mascot?.triggerSuccess('Switched!');
        loadDashboard();
    } catch(e) {
        Mascot?.triggerError('Error');
    }
}

async function activateModel(modelId, providerName) {
    try {
        await API.activateModel(modelId, providerName);
        Mascot?.triggerSuccess('Activated!');
        loadModels(); // Refresh UI to show the active model ✅
    } catch(e) {
        Mascot?.triggerError('Error');
    }
}

// ── Settings ─────────────────────────────────────────────────────────────────
async function loadSettings() {
    try {
        const cfg = await API.getConfig();
        updateToggle('autoRetryToggle2', cfg.auto_retry);
        updateToggle('failoverToggle2', cfg.failover);
        document.getElementById('retryMax').value = cfg.retry_max || 3;
        document.getElementById('checkInterval').value = cfg.check_interval_seconds || 60;
        document.getElementById('portConfig').value = cfg.port || '8082';
    } catch(e) {}
}

async function toggleSetting2(key) {
    const cfg = await API.getConfig();
    const newVal = !cfg[key];
    try {
        await API.updateSetting(key, newVal);
        loadSettings();
        loadDashboard();
    } catch(e) {}
}

async function saveSettings() {
    try {
        const retryMax = parseInt(document.getElementById('retryMax').value) || 3;
        const checkInterval = parseInt(document.getElementById('checkInterval').value) || 60;
        await API.updateSetting('retry_max', retryMax);
        await API.updateSetting('check_interval_seconds', checkInterval);
        nativeAlert('Settings saved');
    } catch(e) { nativeAlert('Failed to save settings'); }
}

async function handleExportConfig() {
    try {
        const data = await API.exportConfig();
        downloadJSON(data, 'claude-proxy-pro-config.json');
    } catch(e) { nativeAlert('Failed to export config'); }
}

async function handleExportLogs() {
    try {
        const data = await API.exportLogs();
        downloadJSON(data, 'claude-proxy-pro-logs.json');
    } catch(e) { nativeAlert('Failed to export logs'); }
}

function downloadJSON(data, filename) {
    const blob = new Blob([data], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
}

// ── Helpers ──────────────────────────────────────────────────────────────────
function updateToggle(id, value) {
    const el = document.getElementById(id);
    if (!el) return;
    if (value) el.classList.add('active'); else el.classList.remove('active');
}

function formatNum(n) {
    return new Intl.NumberFormat().format(n);
}

function esc(s) {
    if(!s) return '';
    return String(s).replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));
}

async function loadSettingsLogs() {
    try {
        const logs = await API.getLogs(50);
        const el = document.getElementById('settingsLog');
        if (!el) return;
        if (!logs || logs.length === 0) {
            el.innerHTML = '<div style="color:var(--text-dim)">[SYSTEM] Awaiting engine initialization...</div>';
            return;
        }
        
        el.innerHTML = logs.map(l => {
            const t = new Date(l.timestamp).toLocaleTimeString();
            const isErr = l.status >= 400;
            const levelCls = isErr ? 'log-error' : 'log-success';
            const levelTxt = isErr ? '[ERROR]' : '[INFO]';
            const msg = `Proxy routed request to ${esc(l.provider)}::${esc(l.model)} - Status: ${l.status} - Latency: ${l.latency_ms}ms`;
            
            return `<div><span class="log-time">${t}</span><span class="${levelCls}">${levelTxt}</span> ${msg}</div>`;
        }).join('');
    } catch(e) {}
}

// ── Init ─────────────────────────────────────────────────────────────────────
// Expose functions globally for onclick handlers
window.showPage = showPage;
window.loadDashboard = loadDashboard;
window.loadLogs = loadLogs;
window.loadModels = loadModels;
window.renderModels = renderModels;
window.setModelFilter = setModelFilter;
window.sortModels = sortModels;
window.loadProviders = loadProviders;
window.renderProviders = renderProviders;
window.showAddProvider = showAddProvider;
window.editProvider = editProvider;
window.hideAddProvider = hideAddProvider;
window.saveProvider = saveProvider;
window.removeProvider = removeProvider;
window.testFromList = testFromList;
window.testCurrentProvider = testCurrentProvider;
window.setProviderFilter = setProviderFilter;
window.discoverAll = discoverAll;
window.switchProvider = switchProvider;
window.activateModel = activateModel;
window.loadSettings = loadSettings;
window.toggleSetting2 = toggleSetting2;
window.saveSettings = saveSettings;
window.handleExportConfig = handleExportConfig;
window.handleExportLogs = handleExportLogs;
window.loadSettingsLogs = loadSettingsLogs;
window.minimizeWindow = () => API.minimizeWindow();
window.maximizeWindow = () => API.maximizeWindow();
window.closeWindow = () => API.closeWindow();

// Expose currentProviders for preset handler
window.currentProviders = currentProviders;

// Safety poll logic to wait for Wails runtime to be fully initialized
function runWhenReady(fn) {
    if (window.go && window.go.main && window.go.main.App) {
        fn();
    } else {
        setTimeout(() => runWhenReady(fn), 30);
    }
}

runWhenReady(() => {
    loadDashboard();
    loadLogs();
    loadSettingsLogs();
    
    // Poll stats
    setInterval(() => { loadDashboard(); loadLogs(); loadSettingsLogs(); }, 5000);
});
