// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActivateModel(arg1:string,arg2:string):Promise<void>;

export function AddProvider(arg1:main.Provider):Promise<void>;

export function CloseWindow():Promise<void>;

export function ConfirmDelete(arg1:string,arg2:string):Promise<boolean>;

export function DiscoverModels():Promise<string>;

export function ExportConfig():Promise<string>;

export function ExportLogs():Promise<string>;

export function GetConfig():Promise<main.AppConfig>;

export function GetHealth():Promise<Record<string, any>>;

export function GetLogs(arg1:number):Promise<Array<main.RequestLog>>;

export function GetModels():Promise<Array<main.ModelInfo>>;

export function GetProviders():Promise<Array<main.Provider>>;

export function GetStats():Promise<Record<string, any>>;

export function GetUptime():Promise<string>;

export function MaximizeWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function RemoveProvider(arg1:number):Promise<void>;

export function ShowAlert(arg1:string,arg2:string):Promise<void>;

export function SwitchProvider(arg1:number):Promise<void>;

export function TestArbitraryProvider(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function TestProvider(arg1:number):Promise<Record<string, any>>;

export function UpdateProvider(arg1:number,arg2:main.Provider):Promise<void>;

export function UpdateSetting(arg1:string,arg2:any):Promise<void>;
