// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateModel(arg1, arg2) {
  return window['go']['main']['App']['ActivateModel'](arg1, arg2);
}

export function AddProvider(arg1) {
  return window['go']['main']['App']['AddProvider'](arg1);
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function ConfirmDelete(arg1, arg2) {
  return window['go']['main']['App']['ConfirmDelete'](arg1, arg2);
}

export function DiscoverModels() {
  return window['go']['main']['App']['DiscoverModels']();
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function ExportLogs() {
  return window['go']['main']['App']['ExportLogs']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHealth() {
  return window['go']['main']['App']['GetHealth']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetUptime() {
  return window['go']['main']['App']['GetUptime']();
}

export function MaximizeWindow() {
  return window['go']['main']['App']['MaximizeWindow']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function RemoveProvider(arg1) {
  return window['go']['main']['App']['RemoveProvider'](arg1);
}

export function ShowAlert(arg1, arg2) {
  return window['go']['main']['App']['ShowAlert'](arg1, arg2);
}

export function SwitchProvider(arg1) {
  return window['go']['main']['App']['SwitchProvider'](arg1);
}

export function TestArbitraryProvider(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestArbitraryProvider'](arg1, arg2, arg3, arg4);
}

export function TestProvider(arg1) {
  return window['go']['main']['App']['TestProvider'](arg1);
}

export function UpdateProvider(arg1, arg2) {
  return window['go']['main']['App']['UpdateProvider'](arg1, arg2);
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['main']['App']['UpdateSetting'](arg1, arg2);
}
